### ISSUE TITLE
Cannot launch GTK Applications

### ISSUE THREAD

**Issue by haecker-felix** [flathub/com.jetbrains.PyCharm-Community#20]
I can't start GTK applications, because the app itself cannot be registered on dbus.

A solution/workaround would be, to add this permission:` --socket=session-bus`

[...]
`Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
`

**Comment by barthalion** [comment]
It would be better to see if access to the bus could be restricted with `--log-session-bus`.

**Comment by haecker-felix** [comment]
Well, the problem is, the dbus service name is variable, because it depends on the application, which is developed by using PyCharm.

http://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access

So i think a restriction would make no sense here.

**Comment by TingPing** [comment]
IDEs are one place we do tend to make that exception so it might be fine.

**Comment by barthalion** [comment]
@haecker-felix Do you think you could submit a pull request with yhis change?

**Comment by haecker-felix** [comment]
Yes, no problem. I'll do it later.

**Comment by haecker-felix** [comment]
@barthalion https://github.com/flathub/com.jetbrains.PyCharm-Community/pull/22
