### ISSUE TITLE
Flatpak blocks access to usb devices

### ISSUE THREAD

**Issue by Split7fire** [flathub/com.jetbrains.PyCharm-Community#31]
I'm writing an app in pycharm for work with usb to serial adapters (like ftdi 232). So in native pycharm my app work as expected (find usb devices), but while in flatpak it don't. Googling the internet I find out that this problem was talked about, but not solved:
https://github.com/flatpak/xdg-desktop-portal/issues/13
https://stackoverflow.com/questions/46518218/trying-to-acces-usb-drive-from-blander-in-a-flatpak-sandbox
https://stackoverflow.com/questions/41252334/accessing-serial-ports-with-an-application-runs-in-flatpak/41286977

Any help?

**Comment by TingPing** [comment]
For now: `flatpak override --user --device=all com.jetbrains.PyCharm-Community`

**Comment by Split7fire** [comment]
@TingPing ok, but what you mean by "for now"? Any ongoing work in flatpak?

**Comment by TingPing** [comment]
For now meaning until this package updates to add it.

**Comment by Split7fire** [comment]
@TingPing ok, thanks for clarifying.
