### ISSUE TITLE
tensorflow compatibility issues with python 3.7

### ISSUE THREAD

**Issue by patriziobruno** [flathub/com.jetbrains.PyCharm-Community#39]
tensorflow is one of the most popular modules in python development, but is not compatible with python 3.7.
I have a project using python 3.5 in a venv, but after upgrading to 2018.2.3 it won't run anymore, because the python 3.5 binaries are compiled against different libraries than the ones available in the freedesktop.Platform runtime. The virtualenv has been created by flatpaked PyCharm 2017 and worked flawlessly until the upgrade.

**Comment by SuborbitalPigeon** [comment]
See https://github.com/tensorflow/tensorflow/issues/17022

**Comment by Red-Eyed** [comment]
So, actually it's not the problem of `flatpak`
Aslo,
