### ISSUE TITLE
how to change the language?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.jetbrains.PyCharm-Community#4]

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by nedrichards** [comment]
This app doesn't have separate locales - so it'd be within the applications settings.

**Comment by joergister** [comment]
@LeandroStanger  afaik this app is only available in English.

**Comment by phracek** [comment]
@LeandroStanger Yes, application is only in English.
