### ISSUE TITLE
Changing theme from 'darcula' causes PyCharm to lock-up

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/com.jetbrains.PyCharm-Community#41]
Hi

I have installed PyCharm 2018.2.3 (community edition) from Flathub on Fedora 28 Workstation. If I then go to File -> Settings -> Appearance and then change the theme from darcula to GTK+ for example, PyCharm then seems to stop responding.

I can make some UI controls work - such as closing the settings window - but I am unable to quit the app and the UI does not work as expected. The new theme also does not appear to take effect.

I'll stick with darcula theme for now but this is a nasty bug which could cause loss of work should a user decide to change their theme without first saving their work.

Thanks, Nick

**Comment by FakeShemp** [comment]
I am able to reproduce.

**Comment by FakeShemp** [comment]
Seems the ability to use a GTK+ theme was removed from upstream in 2018.3, so this is essentially solved :/
