### ISSUE TITLE
where to find com.jetbrains.PyCharm-Community.json

### ISSUE THREAD

**Issue by Monallabs** [flathub/com.jetbrains.PyCharm-Community#482]
I am trying to install PyCharm Community edition on Fedora on Raspberry Pi. 
I have cloned the repo and issued:
```
flatpak-builder --repo=repo flatpakbuildir com.jetbrains.PyCharm-Community.json --force-clean
```
I get the error
```
Can't load 'com.jetbrains.PyCharm-Community.json': Failed to open file “/root/PyCharm/com.jetbrains.PyCharm-Community/com.jetbrains.PyCharm-Community.json”: No such file or directory
```
Am I not using the right approach or is Pycharm not supported on Fedora/Raspberry Pi/arm64?

**Comment by FakeShemp** [comment]
https://flathub.org/apps/details/com.jetbrains.PyCharm-Community

But you are correct; PyCharm is not built for arm64.
