### ISSUE TITLE
icons do not appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.jetbrains.PyCharm-Community#5]

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by nedrichards** [comment]
I'm pretty sure this will be fixed for @LeandroStanger by Endless OS 3.3.5 which will upgrade to Flatpak 0.10.1, can you retest when that's released?

**Comment by LeandroStanger** [comment]
the problem has not been resolved
![captura de tela de 2017-12-12 09-39-05](https://user-images.githubusercontent.com/26097419/33882859-bb4e4c20-df20-11e7-8b41-cd4a9ecc30bf.png)

**Comment by joergister** [comment]
Same here: Icon does not appear in the application dashboard. Neither under KDE (KDE Neon), nor under Gnome (Ubuntu 17.10). 
Flatpak version is 0.10.1 on both systems. 

Application Version on both systems: 

flatpak info com.jetbrains.PyCharm-Community :
> Ref: app/com.jetbrains.PyCharm-Community/x86_64/stable
> ID: com.jetbrains.PyCharm-Community
> Arch: x86_64
> Branch: stable
> Origin: flathub
> Date: 2017-12-12 12:51:21 +0000
> Subject: Update to the latest version (f9e57ce1)
> Commit: 487981acdd6a797b82de2fc51218a1165640f5fed0e7b7d900bf73c1d2b3ccc0
> Parent: b58d27c708ba158587f7b7ee659c5683eef77c8f949a83ec5415b0fc4c0ae8e9
> Location: /var/lib/flatpak/app/com.jetbrains.PyCharm-Community/x86_64/stable/487981acdd6a797b82de2fc51218a1165640f5fed0e7b7d900bf73c1d2b3ccc0
> Installed size: 731,4 MB
> Runtime: org.freedesktop.Sdk/x86_64/1.6


But I have an additionally problem: starting the app from the gui (both, Gnome and KDE) by clicking on the placeholder_for_the_icon does result in a this:



![screenshot_20171212_205230](https://user-images.githubusercontent.com/24881413/33905331-929af036-df7e-11e7-93e3-7a1e2221912f.png)


on both systems.

Starting it from the command-line (on both systems) by typing 

> flatpak run -v com.jetbrains.PyCharm-Community  

gives me this output:

> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening user flatpak installation at path /home/user/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /home/user/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Allowing dri access
> F: Allowing host-fs access
> F: Allowing x11 access
> 
> 

and the application starts perfectly fine. 


oddly enough, when starting from the command line,  the Icon then appears in my Window-List, but only under KDE.

![screenshot_20171212_205818](https://user-images.githubusercontent.com/24881413/33905559-4e35d4f0-df7f-11e7-82b0-2e392d1d6622.png)


Pinning the icon to the window-list (also under KDE), closing the application and clicking again on the Icon results is this:
![x](https://user-images.githubusercontent.com/24881413/33905818-29f7e654-df80-11e7-99e2-71399f5b50db.png)


Pinning the not existing icon (placeholder_for_the_icon) under Gnome (Ubuntu 17.10) to the Ubuntu Dock and trying to start the app by clicking on the placeholder_for_the_icon results in the same window that appears and tells me that the VM option can not be found. 



Last of all: there is a message that appears in Pycharm right after the start of the application that seems to me like something is missing:
![screenshot_20171212_215600](https://user-images.githubusercontent.com/24881413/33908057-77509d9a-df87-11e7-9313-d48be32748aa.png)


Tell me if I can provide any more debug information to help you fix the problem.

**Comment by phracek** [comment]
With the latest PyCharm2017.3 I have java issues. Issue is already filed in PyCHarm https://youtrack.jetbrains.com/issue/PY-27538

**Comment by joergister** [comment]
Any progress here?
I don't think it is the goal of flathub to provide flatpaked programs that can only be started from the command line.

**Comment by joergister** [comment]
An answer would be nice. 
Doesn't matter what this looks like, but this way it is very frustrating. 
I think flathub depends on people, reporting bugs, thus it would be nice to answer them.
