### ISSUE TITLE
NullFunctionError with PyOpenGL

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/com.jetbrains.PyCharm-Community#58]
Hi

I am playing around with PyOpenGL in PyCharm Community edition installed via Flatpak (my host is Fedora 30 Gnome). Running some sample code in PyCharm results in the following error:

`OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective, check for bool(gluPerspective) before calling`

However when running the same code from the host command line or via PyCharm installed from the tarball the code works fine.

Steps to duplicate:
1. Create a new project in PyCharm Community edition 2019.1 Flatpak. Create a new venv.
2. Install pygame and pyopengl via the following commands in the project terminal (i.e. in PyCharm itself):
python3 -m pip install -U pygame
python3 -m pip install -U pyopengl
3. Create cube.py using the code from the following site:
https://pythonprogramming.net/opengl-rotating-cube-example-pyopengl-tutorial/
4. Configure the run environment in PyCharm as follows:
Script Path: [path to cube.py]
Python Interpreter: Project Default (Python 3.7 in the venv I created earlier)
Working Directory: [folder containing cube.py]

The full error received when I attempt to run the code is as follows:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib ../../pulse/pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Traceback (most recent call last):
  File "/home/.../PycharmProjects/PyOpenGL_cube/cube.py", line 64, in <module>
    main()
  File "/home/.../PycharmProjects/PyOpenGL_cube/cube.py", line 47, in main
    gluPerspective(45, (display[0]/display[1]), 0.1, 50.0)
  File "/home/.../PycharmProjects/PyOpenGL_cube/venv/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective, check for bool(gluPerspective) before calling

Process finished with exit code 1
```

This problem seems specific to running the Flatpak PyCharm as the tarball version works fine. Also running pygame code in PyCharm Flatpak also works fine, so the combination of the Flatpaked PyCharm and PyOpenGL seems to be the issue.

Any help with this would be greatly appreciated.

Thanks
Nick

**Comment by FakeShemp** [comment]
Thank you very much for the detailed bug report. The issue seems to be that the glu/glew libraries were missing. This should be fixed in #59 so check for an update on flathub soon.

I also noticed that pulseaudio was missing from your issue, so that is fixed now as well.

Again, thank you :)
