### ISSUE TITLE
Startup Error: Unable to detect graphics environment

### ISSUE THREAD

**Issue by samweisgamdschie** [flathub/com.jetbrains.PyCharm-Community#65]
I get this error message when trying to start pycharm on a remote machine.

I did:
`$ flatpak -v install --user flathub com.jetbrains.PyCharm-Community`

which works fine as a user. But 
```
$ flatpak run com.jetbrains.PyCharm-Community 
debug1: client_input_channel_open: ctype x11 rchan 6 win 65536 max 16384
debug1: client_request_x11: request from ::1 33468
debug1: channel 3: new [x11]
debug1: confirm x11
debug1: channel 3: FORCE input drain
debug1: channel 3: free: x11, nchannels 5
debug1: client_input_channel_open: ctype x11 rchan 6 win 65536 max 16384
debug1: client_request_x11: request from ::1 33470
debug1: channel 3: new [x11]
debug1: confirm x11
debug1: channel 3: FORCE input drain
debug1: channel 3: free: x11, nchannels 5
debug1: client_input_channel_open: ctype x11 rchan 6 win 65536 max 16384
debug1: client_request_x11: request from ::1 33472
debug1: channel 3: new [x11]
debug1: confirm x11
debug1: channel 3: FORCE input drain
debug1: channel 3: free: x11, nchannels 5
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Startup Error: Unable to detect graphics environment
```

I tested to start it with pycharm.sh and it starts at least:
`$ ./.local/share/flatpak/app/com.jetbrains.PyCharm-Community/x86_64/stable/321e66053e28ccb2a10c4641f3a1db0d63bfb1213ebd94ee813e4ac0941ca5a1/files/pycharm/bin/pycharm.sh`

I also did a test with running xpdf from remote and it opens. Btw. with remote I talk about start it over SSH.

Thanks in advance.

**Comment by Red-Eyed** [comment]
It seems that this issue could be closed due to inactivity.

**Comment by Red-Eyed** [comment]
Just checked out: connected to remote `Fedora Silverblue v31` by `SSH` and installed `com.jetbrains.PyCharm-Community`

issue can be closed I guess.

**Comment by BeyMelamed** [comment]
I just encountered same issue upon a new creation of a debian vm using GCP then trying to deploy PyCharm.
After extracting the .gz PyCharm (2020 community version) - to start PyCharm, i issued the console command: 
pycharm-community-2020.1.2/bin/pycharm.sh
There was a bunch of output displayed that ended with:

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Startup Error: Unable to detect graphics environment

So, if you close the issue, please, let me know how to get PyCharm started...

Thanks

**Comment by Red-Eyed** [comment]
Hello @BeyMelamed !
It seems that you downloaded PyCharm as archive from JetBrains site.
But this bug tracker is for the `flatpack` package manager.

So, I guess it's better to report such bug directly to JetBrains [forum](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200379535-PyCharm)

**Comment by BeyMelamed** [comment]
Thanks...
Will look at it later
