### ISSUE TITLE
Package the professional version?

### ISSUE THREAD

**Issue by TingPing** [flathub/com.jetbrains.PyCharm-Community#8]
@phracek Was just wondering if you would be interested in maintaining that version also as I've seen a user request it and it should be effectively the same package.

**Comment by RoyiAvital** [comment]
Could you also add CLion?
It would be great to have CLion as a FlatPak.

**Comment by johanfleury** [comment]
I created a PR for that in: https://github.com/flathub/flathub/pull/1087

**Comment by BjoernDaase** [comment]
> Could you also add CLion?
> It would be great to have CLion as a FlatPak.

If we are already talking about this: I would love to see Rubymine as well.

**Comment by johanfleury** [comment]
You might want to open an issue (or make a PR) on https://github.com/flathub/flathub/

**Comment by BjoernDaase** [comment]
> You might want to open an issue (or make a PR) on https://github.com/flathub/flathub/

Good idea. Here it is https://github.com/flathub/flathub/issues/1090

**Comment by Red-Eyed** [comment]
So, it's already packed and I guess we can close the issue
