### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by Red-Eyed** [flathub/com.jetbrains.PyCharm-Community#85]
How one can actually use this package?
I like `flatpack` but I still have to sit on `snap --classic` version of this app.

This package (Pycharm) is completely unusable in flatpak.

I'm a datascience and use a lot of packages: `pytorch, tensorflow, numpy, pandas, scikit-learn, opencv, CUDA, etc` .

When I want to run my project, I get errors with missing shared libraries that above packages depend on.

Maybe this application can be used for hello words, but I can't make it work for no "pure python" projects.

Is there any workaround for such type of applications (IDE like)
Or I should just give up and use `snap --classic` ?

PS: Yes, I've found similar issues and it seams that I should give up, but I just want to make it finally clear: can I use IDE in `flatpak` or not.
Just wonder, how does `gnome.Builder` works. I guess it uses something like "host-spawn" but didn't find it in the sources.

@TingPing what can you say about this?

Thanks!

**Comment by FakeShemp** [comment]
Though not the best solution, you can at least ignore venv's and use the system python and libraries.

If there are just some straggler libraries missing, I don't see a problem to adding them in the manifests. And above that, there is always the possibility of extensions.

**Comment by Red-Eyed** [comment]
Usage of system python is impossible, project dependencies could take up to 10 GB
different projects has it's own set of deps with different versions and cannot intersect.

And yes, if IDE dictates me how to program and organize project: get rid of that IDE.

**Comment by Red-Eyed** [comment]
Regarding extension:
IDE is just like text editor and debug visualizer.
So, python projects works fine w/o any IDE and IDE is optional.

Extensions are just more dependencies, that's awful.

**Comment by FakeShemp** [comment]
Libraries are dependencies. They need to be available somewhere.

**Comment by FakeShemp** [comment]
Do you know which package need `libgcc_s.so.1` so that I can test it?

**Comment by Red-Eyed** [comment]
shapely

**Comment by Red-Eyed** [comment]
I can actually send you traceback:
```
    from shapely import geometry
  File "/home/redeyed/miniconda3/envs/gen3/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/redeyed/miniconda3/envs/gen3/lib/python3.7/site-packages/shapely/geometry/base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/redeyed/miniconda3/envs/gen3/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/home/redeyed/miniconda3/envs/gen3/lib/python3.7/site-packages/shapely/geos.py", line 92, in <module>
    free = load_dll('c', fallbacks=c_alt_paths).free
  File "/home/redeyed/miniconda3/envs/gen3/lib/python3.7/site-packages/shapely/geos.py", line 62, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants ['libc.musl-x86_64.so.1'].

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by FakeShemp** [comment]
Thanks :)

**Comment by Red-Eyed** [comment]
Frankly speaking, the question was not in this particular error. Because this error is just a reason of sandboxed environment.

But more like: "how one could use `flatpak` version of PyCharm with access to all system env?"

**Comment by FakeShemp** [comment]
Yes, I understand that, but I'm curious about it. And I need some issue to start looking at the problem from.

**Comment by Red-Eyed** [comment]
Got it.

**Comment by FakeShemp** [comment]
Conda seem to be missing from this manifest. With a new virtualenv I didn't have the same issues as you.

I have no experience with Conda. Does it load libraries differently than venv?

I know there are issues with sandboxing the IDE, I've [made issues about it myself](https://github.com/flathub/com.jetbrains.PyCharm-Community/issues/84), but I'm thinking that they might be extra bad with a Conda environment.

I'll look into adding Conda too the manifest as soon as I can. It should be included anyway.

**Comment by Red-Eyed** [comment]
Strange error
I've reproduced it and have minimal complete example:
I use `python 3.7.4`
```
pip install -U pyqt5
pip install -U "shapely[vectorized]"

test.py
from PyQt5 import Qt
from shapely import geometry
```

**Comment by Red-Eyed** [comment]
> I'll look into adding Conda too the manifest as soon as I can. It should be included anyway.
What do u mean by manifest?
U mean to include `conda` as extension?
If so, it's not required and will be redundant.

I used only `pypi` and didn't use `conda` package manager
used it only to install python and create `venv`

**Comment by FakeShemp** [comment]
The flatpak manifest. The thing that tells flatpak how to install this app.

Conda would be bundled with this flatpak app by default since it's available for use directly in PyCharm. Right now it just complain that the Conda executable isn't found.

**Comment by Red-Eyed** [comment]
Whoa, it seems that everything works fine, when I changed order of imports (first `shapely` than `qt`)
Even heavy project with 8GB deps works like a charm in `flatpak` PyCharm.

Taking in mind sandbox, I though that such an error is just on of possible error in sandbox.

**Comment by Red-Eyed** [comment]
> Right now it just complain that the Conda executable isn't found.

So, I've just installed conda locally (used [this script](https://github.com/Red-Eyed/ConfigFiles/blob/master/install_python.sh)) and don't have any problems with conda.

**Comment by Red-Eyed** [comment]
So now I can finally get rid of `snap`, as problem is weakly related to `flatpak` and `sandbox`
It seems that `from PyQt5 import Qt` makes `shapely` "blind" and it cannot find `libc`

**Comment by Red-Eyed** [comment]
I'm closing this issue, as problem is not related to `flatpak` version of PyCharm.

Thanks to @FakeShemp for the help!
