### ISSUE TITLE
Needs a 128x128 icon for the apps page

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.jetbrains.PyCharm-Community#9]
In order to look nice on the [apps page](https://beta.flathub.org/apps) this needs a 128x128 icon. Furthermore, there appears to be a separate bug where the apps page doesn't show anything because we also don't have a 64x64px icon here.

@jgarciao FYI another case that might be worth considering!

**Comment by FakeShemp** [comment]
Solved upstream and solved here in #36.
